function createfigure(X1, Y1, YNeg1, XNeg1, X2, Y2)
%CREATEFIGURE(X1, Y1, YNeg1, XNeg1, X2, Y2)
%  X1:  errorbar x vector data
%  Y1:  errorbar y vector data
%  YNEG1:  errorbar ynegativedelta vector data
%  XNEG1:  errorbar xnegativedelta vector data
%  X2:  vector of x data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 29-Aug-2022 00:54:25

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create errorbar
errorbar(X1,Y1,YNeg1,YNeg1,XNeg1,XNeg1,'DisplayName','forced vortex',...
    'MarkerFaceColor',[1 0 0],...
    'MarkerEdgeColor','none',...
    'Marker','o',...
    'LineStyle','none',...
    'LineWidth',1,...
    'Color',[0 0 0]);

% Create plot
plot(X2,Y2,'DisplayName','theory','Color',[0 0 1]);

% Create ylabel
ylabel('Height of interface [cm]');

% Create xlabel
xlabel('Radial position [cm]');

% Create title
title('Forced Vortex 130 rpm');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 20]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[20 32]);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'GridAlpha',0.5,'MinorGridAlpha',0.4,'XMinorGrid','on',...
    'YMinorGrid','on','ZMinorGrid','on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','southeast');

